name: flutter_command_todo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_command: ^2.0.0
  get_it: ^6.1.1
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner:

flutter:
  uses-material-design: true
